site_name: IT-Wiki
theme:
  language: de
  icon:
      repo: fontawesome/brands/git-alt
  name: material
  custom_dir: overrides
  logo: assets/img/logo.svg
  favicon: assets/img/favicon-white.ico
  font:
    text: IBM Plex Sans
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.code.link
    - content.footnote.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  static_templates:
    - 404.html

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Wechseln zum dunklen Modus

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Wechseln zum hellen Modus

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: MATrsx/wiki
      branch: main
  - git-authors

nav:
  - Einf√ºhrung: index.md
  - Customization: customization.md
  - Markdown Syntax: md_syntax.md 
  - Projektmanagement: 
    - ü¶äGit(Lab): project_management/git.md
  - Programmierung:
    - üêçPython: programming/python.md
  - Datenbanken:
    - üì´PostgreSQL: databases/postgresql.md
  - Speicherung:
    - Elektronische Datenspeicher: memory/electronic_data_storage.md
    - Magnetische Datenspeicher: memory/magnetic_data_storage.md
    - Optische Datenspeicher: memory/optical_data_storage.md
    - RAID-Systeme: memory/raid.md
    - Cloudspeicher: memory/cloud.md
  - Mathematik:
    - Generell: maths/general.md
  - Diagramme & Darstellungen:
    - Sequenzdiagramm: diagrams/sequence_diagram.md
    - Aktivit√§tsdiagramm: diagrams/activity_diagram.md

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/admonitions.css
  - https://cdn.datatables.net/2.0.2/css/dataTables.dataTables.css

extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.slim.min.js
  - https://cdn.datatables.net/2.0.2/js/dataTables.js
  - assets/scripts/site.js

#Repository
repo_name: IT-Wiki
repo_url: https://github.com/MATrsx/wiki
edit_uri: https://github.com/MATrsx/wiki/tree/main/docs
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      toc_depth: 3
      permalink: 'üîó'

#footer
extra:
  generator: false
  # social:
  #   - icon: material/email 
  #     link: mailto:vkuschew@phoenixcontact.com
  #     name: Fragen zu der Dokumentation?